services:
  postgres:
    image: postgres:16
    container_name: ayvalikbank-ha-python-postgres
    environment:
      POSTGRES_DB: ayvalikbank_ha_python
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
